/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * AUTO-GENERATO da MODULI/Onirico_Task_Library.xlsx — non modificare a mano.
 * Catalogo dei task operativi di tutte le società (Onirico/Materico/Unico/Strategico).
 */

export type Society = 'Onirico' | 'Materico' | 'Unico' | 'Strategico';
export type TaskType = 'Produzione' | 'Burocrazia' | 'Controllo' | 'Gestione';
export type Complexity = 'Bassa' | 'Media' | 'Alta';

export interface LibraryTask {
  society: Society;
  fase: string;
  categoria: string;
  task: string;
  tipo: TaskType;
  hours: number;
  complexity: Complexity;
  repetitive: boolean;
  recurring: boolean;
  note?: string;
}

export const TASK_LIBRARY: LibraryTask[] = [
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Rilievo', task: 'Laser scanner in situ', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Rilievo', task: 'Allineamento nuvola', tipo: 'Produzione', hours: 1.5, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Rilievo', task: 'Restituzione grafica', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Rilievo', task: 'Rilievo materico', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Rilievo', task: 'Indagine termografica', tipo: 'Controllo', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Studio di fattibilità', task: 'Verifica edificabilità terreni', tipo: 'Controllo', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Studio di fattibilità', task: 'Verifica legittimità fabbricati', tipo: 'Controllo', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Studio di fattibilità', task: 'Proposta di sanatoria', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Studio di fattibilità', task: 'Studio fattibilità fotovoltaico', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Studio di fattibilità', task: 'Presentazione di supporto a riunione', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Analisi esigenze e considerazioni', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Progetto di massima e calcoli volumetrici', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Moodboard e riferimenti', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Planimetria (Fascia 1)', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Planimetria (Fascia 2)', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Planimetria (Fascia 3)', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Pianta (Fascia 1)', tipo: 'Produzione', hours: 16, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Pianta (Fascia 2)', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Pianta (Fascia 3)', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Prospetti (Fascia 1)', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Prospetti (Fascia 2)', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Prospetti (Fascia 3)', tipo: 'Produzione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Sezioni (Fascia 1)', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Sezioni (Fascia 2)', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Sezioni (Fascia 3)', tipo: 'Produzione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Particolari esecutivi (Fascia 1)', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Particolari esecutivi (Fascia 2)', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '2D Particolari esecutivi (Fascia 3)', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Variante sostanziale', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Variante lievi modifiche', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '3D Modellazione (Fascia 1)', tipo: 'Produzione', hours: 14, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '3D Modellazione (Fascia 2)', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '3D Modellazione (Fascia 3)', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '3D Render (Fascia 1)', tipo: 'Produzione', hours: 16, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '3D Render (Fascia 2)', tipo: 'Produzione', hours: 12, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: '3D Render (Fascia 3)', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Supporto al renderista', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Computo metrico architettonico (Fascia 1)', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Computo metrico architettonico (Fascia 2)', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Computo metrico architettonico (Fascia 3)', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Capitolato opere architettoniche', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Abaco infissi', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Architettonico', task: 'Elenco prezzi - Prezziario Regionale', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Strutturale', task: 'Modellazione strutturale, calcolo, relazioni e tavole (F1)', tipo: 'Produzione', hours: 10, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Strutturale', task: 'Modellazione strutturale, calcolo, relazioni e tavole (F2)', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Strutturale', task: 'Modellazione strutturale, calcolo, relazioni e tavole (F3)', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Strutturale', task: 'Computo metrico strutturale (Fascia 1)', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Strutturale', task: 'Computo metrico strutturale (Fascia 2)', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Strutturale', task: 'Computo metrico strutturale (Fascia 3)', tipo: 'Produzione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Schema impianto elettrico', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Schema impianto fotovoltaico', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Schema impianto adduzione acqua', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Schema impianto scarico', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Schema impianto termico', tipo: 'Produzione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Schema impianto clima', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Schema impianto VMC', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Schema impianto gas', tipo: 'Produzione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Schema carichi termici', tipo: 'Produzione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Aggiornamento complessivo schemi impiantistici', tipo: 'Produzione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Progetto impianto termico', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Progetto impianto VMC', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Progetto impianto elettrico', tipo: 'Produzione', hours: 16, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Progetto impianto fotovoltaico', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Computo metrico impiantistico (Fascia 1)', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Computo metrico impiantistico (Fascia 2)', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Impiantistico', task: 'Computo metrico impiantistico (Fascia 3)', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Progettazione', categoria: 'Perizie', task: 'Perizia immobiliare', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'CILA - Modello', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'CILA - Relazione tecnica', tipo: 'Burocrazia', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'CILA - Tavola 1', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'CILA - Tavola 2', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'CILA - Trasmissione SUET', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'SCIA - Modello', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'SCIA - Relazione tecnica', tipo: 'Burocrazia', hours: 5, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'SCIA - Tavola 1', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'SCIA - Tavola 2', tipo: 'Burocrazia', hours: 5, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'SCIA - Trasmissione SUET', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'P.d.C. - Modello', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'P.d.C. - Relazione tecnica', tipo: 'Burocrazia', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'P.d.C. - Tavola 1', tipo: 'Burocrazia', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'P.d.C. - Tavola 2', tipo: 'Burocrazia', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'P.d.C. - Trasmissione SUET', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'Integrazione pratica', tipo: 'Burocrazia', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'Comunicazione inizio lavori architettonica', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'Autorizzazione allo scarico', tipo: 'Burocrazia', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'Agibilità', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica edilizia', task: 'Comunicazione fine lavori', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica ASL', task: 'Richiesta parere ASL e layout attrezzature', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica paesaggistica', task: 'Accertamento compatibilità paesaggistica', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica paesaggistica', task: 'Relazione paesaggistica', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica paesaggistica', task: 'Schede conoscitive', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica energetica', task: 'Legge 10', tipo: 'Burocrazia', hours: 5, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica energetica', task: 'APE', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica energetica', task: 'AQE', tipo: 'Burocrazia', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica energetica', task: 'ENEA', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica energetica', task: 'Pratica fotovoltaico e GSE', tipo: 'Burocrazia', hours: 12, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica energetica', task: 'Protocollo Itaca', tipo: 'Burocrazia', hours: 16, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica strutturale', task: 'Pratica strutturale (Fascia 1)', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica strutturale', task: 'Pratica strutturale (Fascia 2)', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica strutturale', task: 'Pratica strutturale (Fascia 3)', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica strutturale', task: 'Denuncia sismica', tipo: 'Burocrazia', hours: 1.5, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica strutturale', task: 'Comunicazione inizio lavori strutturali', tipo: 'Burocrazia', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica strutturale', task: 'Relazione a strutture ultimate', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica strutturale', task: 'Collaudo statico', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Accatastamento', task: 'Elaborazione Tipo Mappale', tipo: 'Burocrazia', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Accatastamento', task: 'Elaborazione DOCFA', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Accatastamento', task: 'Gestione Tipo Mappale e DOCFA', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Accatastamento', task: 'Istanze catastali', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica produttiva', task: 'Occupazione suolo pubblico - Relazione tecnica', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica produttiva', task: 'Occupazione suolo pubblico - Tavola grafica', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica produttiva', task: 'Trasmissione SUAP', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica insegna', task: 'INSEGNA - Modello', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica insegna', task: 'INSEGNA - Relazione tecnica', tipo: 'Burocrazia', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica insegna', task: 'INSEGNA - Tavola grafica', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Pratica insegna', task: 'INSEGNA - Trasmissione Ufficio Tributi', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Comunicazioni', task: 'Invio istanze, nulla osta e PEC', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Comunicazioni', task: 'Notifica preliminare ASL e Ispettorato', tipo: 'Burocrazia', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Comunicazioni', task: 'Richiesta CDU', tipo: 'Burocrazia', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Bandi', task: 'Mini PIA - Scheda cantierabilità', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Collaudi', task: 'Certificato di idoneità statica', tipo: 'Burocrazia', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Contabilità', task: 'Contratto d\'appalto', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Burocrazia', categoria: 'Contabilità', task: 'Richiesta preventivo all\'impresa', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Rilievo cantiere', task: 'Laser scanner in situ - Cantiere', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Rilievo cantiere', task: 'Allineamento nuvola - Cantiere', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Rilievo cantiere', task: 'Restituzione grafica cantiere', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Sicurezza', task: 'CSP - Piano di sicurezza e coordinamento (F1)', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Sicurezza', task: 'CSP - Piano di sicurezza e coordinamento (F2)', tipo: 'Burocrazia', hours: 1.5, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Sicurezza', task: 'CSP - Piano di sicurezza e coordinamento (F3)', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Sicurezza', task: 'CSE - Verifica e aggiornamento documentazione', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Sicurezza', task: 'Cartello di cantiere', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Sicurezza', task: 'Verifica PSC/POS/Fascicolo', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Sicurezza', task: 'Verifica Pi.M.U.S.', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Sicurezza', task: 'Notifica preliminare cantiere', tipo: 'Burocrazia', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Sopralluogo ordinario semplice', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Sopralluogo ordinario medio', tipo: 'Controllo', hours: 1.5, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Sopralluogo ordinario complesso', tipo: 'Controllo', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Sopralluogo straordinario semplice', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Sopralluogo straordinario medio', tipo: 'Controllo', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Sopralluogo straordinario complesso', tipo: 'Controllo', hours: 5, complexity: 'Alta', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Tracciamento semplice', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Tracciamento medio', tipo: 'Controllo', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Tracciamento complesso', tipo: 'Controllo', hours: 5, complexity: 'Alta', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cantiere', task: 'Assistenza programmazione domotica', tipo: 'Controllo', hours: 4, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cliente', task: 'Assistenza scelta materiali semplice', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cliente', task: 'Assistenza scelta materiali media', tipo: 'Controllo', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cliente', task: 'Assistenza scelta materiali complessa', tipo: 'Controllo', hours: 5, complexity: 'Alta', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cliente', task: 'Aggiornamento cliente', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Assistenza cliente', task: 'Report settimanale al cliente', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'ENEL', task: 'Sopralluogo spostamento impianti', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'ENEL', task: 'Pratica spostamento impianti', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Contabilità cantiere', task: 'Controllo fattura impresa', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Contabilità cantiere', task: 'Dichiarazione IVA agevolata', tipo: 'Burocrazia', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Controllo tracciamento prima scavo', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Controllo scavo pulito e magrone', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica casseratura', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica armatura prima del getto', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Controllo copriferro armature', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica staffe nei nodi trave-pilastro', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Controllo allineamento pilastri', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Controllo vibrazione getto', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica prelievo provini', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica nidi d\'ape', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica assenza acqua aggiunta nel getto', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Controllo maturazione provini', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Invio provini al laboratorio (entro 45gg)', tipo: 'Burocrazia', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Controllo messa a terra', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica cordolo di coronamento', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica appoggi travi', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica fori, cavedi e aerazioni', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica interferenze struttura-impianti', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica compatibilità struttura-architettura', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Cantiere', categoria: 'Controllo strutture', task: 'Verifica necessità variante in cantiere', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Diagnosi', task: 'Analisi quadro fessurativo', tipo: 'Controllo', hours: 1.5, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Diagnosi', task: 'Verifica lesioni da schiacciamento', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Diagnosi', task: 'Verifica lesioni da cedimento fondale', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Diagnosi', task: 'Verifica cinematismi locali', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Diagnosi', task: 'Verifica architravi nascosti', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Diagnosi', task: 'Diagnosi strutturale su esistente', tipo: 'Controllo', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Diagnosi', task: 'Saggi fondali', tipo: 'Controllo', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Intervento', task: 'Cerchiature in acciaio', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Intervento', task: 'Iniezioni cementizie', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Intervento', task: 'Cuci-scuci', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Intervento', task: 'Passivazione ferri', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Intervento', task: 'Malte tixotropiche', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Intervento', task: 'FRP - Fibra di carbonio', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Intervento', task: 'FRCM - Fibra con matrice cementizia', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Intervento', task: 'Sottomurazione', tipo: 'Produzione', hours: 6, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Restauro', categoria: 'Intervento', task: 'Micropali', tipo: 'Produzione', hours: 8, complexity: 'Alta', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Pipeline', task: 'Primo contatto cliente', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Pipeline', task: 'Indagine bisogni cliente', tipo: 'Gestione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Pipeline', task: 'Verifica budget cliente', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Pipeline', task: 'Preparazione proposta commerciale', tipo: 'Gestione', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Pipeline', task: 'Presentazione preventivo', tipo: 'Gestione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Pipeline', task: 'Gestione obiezioni', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Pipeline', task: 'Chiusura incarico', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Pipeline', task: 'Follow-up cliente', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Pipeline', task: 'Segnalazione nuovo cliente', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Documenti', task: 'Preparazione brochure o scheda tecnica', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Onirico', fase: 'Vendita', categoria: 'Documenti', task: 'Raccolta documenti cliente per avvio pratica', tipo: 'Gestione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Richiesta', categoria: 'Cliente', task: 'Ricezione richiesta cliente', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Richiesta', categoria: 'Cliente', task: 'Verifica dati e documenti mancanti', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Richiesta', categoria: 'Cliente', task: 'Inserimento quantità manuali', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Richiesta', categoria: 'Cliente', task: 'Inserimento link prodotto', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Richiesta', categoria: 'Cliente', task: 'Inserimento note cliente', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Richiesta', categoria: 'Cliente', task: 'Classificazione tipologia lavorazione', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Selezione partner', categoria: 'Partner', task: 'Visualizzazione partner suggeriti', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Selezione partner', categoria: 'Partner', task: 'Selezione partner da contattare', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Selezione partner', categoria: 'Partner', task: 'Modifica e invio richiesta preventivo ai partner', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Gestione offerte', categoria: 'Offerte', task: 'Ricezione offerte dai partner', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Gestione offerte', categoria: 'Offerte', task: 'Comparazione automatica offerte', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Gestione offerte', categoria: 'Offerte', task: 'Selezione offerta migliore', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Preventivo cliente', categoria: 'Preventivo', task: 'Applicazione percentuale Materico', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Preventivo cliente', categoria: 'Preventivo', task: 'Generazione preventivo finale', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Preventivo cliente', categoria: 'Preventivo', task: 'Invio preventivo al cliente', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Contrattualistica', categoria: 'Contratti', task: 'Autocompilazione contratto cliente', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Contrattualistica', categoria: 'Contratti', task: 'Autocompilazione contratto partner', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Contrattualistica', categoria: 'Contratti', task: 'Invio per firma digitale', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Contrattualistica', categoria: 'Contratti', task: 'Archiviazione contratti firmati', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Lavori in corso', categoria: 'Esecuzione', task: 'Conferma avvio lavori al partner', tipo: 'Gestione', hours: 0.25, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Lavori in corso', categoria: 'Esecuzione', task: 'Monitoraggio avanzamento lavorazioni', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Lavori in corso', categoria: 'Esecuzione', task: 'Verifica qualità in corso d\'opera', tipo: 'Controllo', hours: 1.5, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Lavori in corso', categoria: 'Esecuzione', task: 'Ricezione e controllo fattura partner', tipo: 'Controllo', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Lavori in corso', categoria: 'Esecuzione', task: 'Emissione fattura cliente', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Materico', fase: 'Lavori in corso', categoria: 'Esecuzione', task: 'Chiusura commessa e archiviazione', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Scouting', categoria: 'Acquisizione', task: 'Ricerca immobile target', tipo: 'Gestione', hours: 4, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Scouting', categoria: 'Acquisizione', task: 'Analisi catastale e urbanistica', tipo: 'Controllo', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Scouting', categoria: 'Acquisizione', task: 'Verifica legittimità e conformità', tipo: 'Controllo', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Scouting', categoria: 'Acquisizione', task: 'Stima costi ristrutturazione (con Materico)', tipo: 'Gestione', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Scouting', categoria: 'Acquisizione', task: 'Simulazione ROI per gli investitori', tipo: 'Gestione', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Scouting', categoria: 'Acquisizione', task: 'Raccolta manifestazioni di interesse investitori', tipo: 'Gestione', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Scouting', categoria: 'Acquisizione', task: 'Costituzione SPV', tipo: 'Burocrazia', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Unico', fase: 'Scouting', categoria: 'Acquisizione', task: 'Rogito/acquisto immobile', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Unico', fase: 'Ristrutturazione', categoria: 'Esecuzione', task: 'Apertura commessa Materico collegata', tipo: 'Gestione', hours: 0.5, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Ristrutturazione', categoria: 'Esecuzione', task: 'Supervisione avanzamento lavori', tipo: 'Controllo', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Ristrutturazione', categoria: 'Esecuzione', task: 'Approvazione SAL e pagamenti', tipo: 'Controllo', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Ristrutturazione', categoria: 'Esecuzione', task: 'Collaudo finale', tipo: 'Controllo', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Ristrutturazione', categoria: 'Esecuzione', task: 'Agibilità immobile', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Unico', fase: 'Vendita', categoria: 'Post-ristrutturazione', task: 'Valutazione immobile post-lavori', tipo: 'Gestione', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Vendita', categoria: 'Post-ristrutturazione', task: 'Pubblicazione e marketing (con Strategico)', tipo: 'Gestione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Vendita', categoria: 'Post-ristrutturazione', task: 'Gestione trattative acquirente', tipo: 'Gestione', hours: 3, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Vendita', categoria: 'Post-ristrutturazione', task: 'Rogito vendita', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Unico', fase: 'Vendita', categoria: 'Post-ristrutturazione', task: 'Calcolo e distribuzione rendimenti investitori', tipo: 'Gestione', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Unico', fase: 'Vendita', categoria: 'Post-ristrutturazione', task: 'Chiusura SPV e archiviazione', tipo: 'Burocrazia', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Onirico', task: 'Brief strategia comunicazione', tipo: 'Gestione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: true },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Onirico', task: 'Pianificazione editoriale mensile', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Contenuti', task: 'Produzione post social strutturato', tipo: 'Produzione', hours: 1.5, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Contenuti', task: 'Produzione storia/reel', tipo: 'Produzione', hours: 1, complexity: 'Bassa', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Contenuti', task: 'Intervento in video aziendale', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Contenuti', task: 'Supporto testi e immagini blog/sito', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Contenuti', task: 'Ottimizzazione SEO contenuti', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Documenti', task: 'Creazione presentazione commerciale', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Documenti', task: 'Ottimizzazione presentazione esistente', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Documenti', task: 'Creazione/aggiornamento mansionario', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Documenti', task: 'Creazione/revisione procedura interna', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing interno', categoria: 'Documenti', task: 'Aggiornamento brand identity', tipo: 'Produzione', hours: 4, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing esterno', categoria: 'Clienti', task: 'Onboarding nuovo cliente marketing', tipo: 'Gestione', hours: 2, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Strategico', fase: 'Marketing esterno', categoria: 'Clienti', task: 'Analisi brand e target', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing esterno', categoria: 'Clienti', task: 'Proposta piano marketing', tipo: 'Produzione', hours: 3, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing esterno', categoria: 'Clienti', task: 'Campagne Meta Ads', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing esterno', categoria: 'Clienti', task: 'Campagne Google Ads', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing esterno', categoria: 'Clienti', task: 'Produzione contenuti grafici', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing esterno', categoria: 'Clienti', task: 'Report mensile performance', tipo: 'Produzione', hours: 2, complexity: 'Media', repetitive: true, recurring: false },
  { society: 'Strategico', fase: 'Marketing esterno', categoria: 'Clienti', task: 'Riunione di allineamento con cliente', tipo: 'Gestione', hours: 1.5, complexity: 'Media', repetitive: true, recurring: true },
  { society: 'Strategico', fase: 'Marketing esterno', categoria: 'Clienti', task: 'Ottimizzazione campagne', tipo: 'Produzione', hours: 1.5, complexity: 'Media', repetitive: true, recurring: false },
];
